# Generated by Django 4.0.4 on 2022-04-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_discord_id_alter_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='clp',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cny',
        ),
        migrations.RemoveField(
            model_name='account',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lir',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp',
        ),
    ]
