# Generated by Django 4.0.4 on 2022-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uczniowie',
            fields=[
                ('id_ucznia', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id ucznia')),
                ('numer_w_dzienniku', models.PositiveIntegerField(default=0, verbose_name='Numer w dzienniku')),
                ('imie', models.CharField(max_length=64, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('klasa', models.CharField(choices=[('1a_gr1', 'Klasa 1a grupa 1'), ('1a_gr2', 'Klasa 1a grupa 2'), ('1b_gr1', 'Klasa 1b grupa 1'), ('1b_gr2', 'Klasa 1b grupa 2')], max_length=64, verbose_name='Klasa')),
            ],
        ),
    ]
