# Generated by Django 4.0.4 on 2022-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obecnosc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uczniowie',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='uczniowie',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='uczniowie',
            name='nazwisko_imie',
            field=models.CharField(default='', max_length=128, verbose_name='Imie i nazwisko'),
        ),
    ]
