# Generated by Django 4.0.4 on 2022-04-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obecnosc', '0002_remove_uczniowie_imie_remove_uczniowie_nazwisko_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obecnosci',
            fields=[
                ('id_obecnosci', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id obecnosci')),
                ('status', models.CharField(choices=[('OB', 'Obecny'), ('ZW', 'Zwolniony'), ('BS', 'Brak Stroju'), ('NB', 'Nieobecny')], max_length=64, verbose_name='Status')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data sprawdzania')),
                ('uczen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Uczen', to='obecnosc.uczniowie', verbose_name='Uczeń')),
            ],
        ),
    ]
