# Generated by Django 4.0.4 on 2022-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obecnosc', '0003_obecnosci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczniowie',
            name='klasa',
            field=models.CharField(choices=[('1a_gr1', 'Klasa 1a grupa 1'), ('1a_gr2', 'Klasa 1a grupa 2'), ('1b_gr1', 'Klasa 1b grupa 1'), ('1b_gr2', 'Klasa 1b grupa 2'), ('1c_gr1', 'Klasa 1c grupa 1'), ('1c_gr2', 'Klasa 1c grupa 2'), ('1t_gr1', 'Klasa 1t grupa 1'), ('1t_gr2', 'Klasa 1t grupa 2'), ('2a_gr1', 'Klasa 2a grupa 1'), ('2a_gr2', 'Klasa 2a grupa 2'), ('2b_gr1', 'Klasa 2b grupa 1'), ('2b_gr2', 'Klasa 2b grupa 2'), ('2c_gr1', 'Klasa 2c grupa 1'), ('2c_gr2', 'Klasa 2c grupa 2'), ('2t_gr1', 'Klasa 2t grupa 1'), ('2t_gr2', 'Klasa 2t grupa 2'), ('3a_gr1', 'Klasa 3a grupa 1'), ('3a_gr2', 'Klasa 3a grupa 2'), ('3b_gr1', 'Klasa 3b grupa 1'), ('3b_gr2', 'Klasa 3b grupa 2'), ('3c_gr1', 'Klasa 3c grupa 1'), ('3c_gr2', 'Klasa 3c grupa 2'), ('3t_gr1', 'Klasa 3t grupa 1'), ('3t_gr2', 'Klasa 3t grupa 2'), ('4a_gr1', 'Klasa 4a grupa 1'), ('4a_gr2', 'Klasa 4a grupa 2'), ('4b_gr1', 'Klasa 4b grupa 1'), ('4b_gr2', 'Klasa 4b grupa 2'), ('4c_gr1', 'Klasa 4c grupa 1'), ('4c_gr2', 'Klasa 4c grupa 2'), ('4t_gr1', 'Klasa 4t grupa 1'), ('4t_gr2', 'Klasa 4t grupa 2'), ('5t_gr1', 'Klasa 5t grupa 1'), ('5t_gr2', 'Klasa 5t grupa 2')], max_length=64, verbose_name='Klasa'),
        ),
    ]
